### ISSUE TITLE
Touch support?

### ISSUE THREAD

**Issue by Almo7aya** [luvsic3/remind#6]
It would be so great if the package supports touch screens, so we can use it on mobile, and hyperd frameworks.

**Comment by unhandledrejection** [comment]
What's your use case ? support mobile will be some challenge both to developer and editor user  
Will downgrade to readonly mindmap on mobile device fill your usage ?

**Comment by Almo7aya** [comment]
The package freezes on mobiles, I couldn't even move the viewport, If is so hard to support the touch events at least it should support the basic navigation logic

**Comment by unhandledrejection** [comment]
@Almo7aya This is a bug,I'm going to fix this.Thank your feedback
